### ISSUE TITLE
Disable debugging logs

### ISSUE THREAD

**Issue by tiphedor** [karl-rousseau/HybridTvViewer#17]
Hello, 

I'd like a way to disable the debug logging that is spamming the console. It looks like there is a `_DEBUG_` flag, but it seem to be hardcoded to true, with no way that i could find to disable it.

Is there a solution that i'm missing ? :)

Thanks a lot !

**Comment by karl-rousseau** [comment]
Hi,

You are right and I am removing this flag as I already did externalize this part of code (in a proper ES6 module) that I need to commit. I have also converted most console.log to console.timeStamp in order to see them inside devtools performance inspector panel (i.e. only useful for HbbTV developers)

Regards.
