### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by ZiTAL** [karl-rousseau/HybridTvViewer#2]
I used this to install it:

https://superuser.com/a/252990/200128

But I think that is better to put it in the README.

**Comment by karl-rousseau** [comment]
Sure but since its start, it was a prototype in mind. Now I am cleaning (also adding unit testing) and porting the code to Firefox as it is using the same framework **WebExtension** and I will package this project in a proper extension exposed on **Opera store** and also **Firefox store**. (I had some tiny bugs on Firefox that I have just fixed)

**Comment by ZiTAL** [comment]
great, thank for all, the extension is awesome!

**Comment by karl-rousseau** [comment]
The code has been fixed to be working on Firefox and even under Android (tested on Nvidia Shield)
I have tagged this version 0.3 and it has just been published on Firefox store so you can now install it easily and rate it ;)
https://addons.mozilla.org/en-US/firefox/addon/hybridtvviewer/

Next release will better support video and HbbTV features. I will also avoid to create buttons in the DOM of the application (which is messing its design and it is also hard for the developer to figure out what is his stuff versus the extension one)
Enjoy
