### ISSUE TITLE
How to test the actual status in Firefox

### ISSUE THREAD

**Issue by Bond246** [karl-rousseau/HybridTvViewer#3]
Hello,

it's nice to see that there are new developments for testing HbbTV Applications on PC. Since Firefox 57 FireHbbTV is not working anymore and so i'm glad so see this project.

What is the actual status? Why is the plugin not available anymore in the Firefox Addon-Base? Im not really familiar with exporting git-projects to XPI-Files for Firefox. An exported release in this repository would be nice.

Thanks,
Bond

**Comment by karl-rousseau** [comment]
Thank you for the interest on the project and to be honest, I was surprised to see the plugin being rejected (even previous releases) in an unexpected review because of the integration of the library Dash.JS in minified version without the associated sources. I am fixing this pretty soon with a new version 0.5
